    - name: Copy .env file
      run: cp .env.example .env

    - name: Update .env for MySQL
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing_db/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=user/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Install Node.js dependencies
      run: npm install

    - name: Build frontend assets
      run: npm run build

    - name: Generate application key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Clear config cache
      run: php artisan config:clear

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: testing_db
        DB_USERNAME: user
        DB_PASSWORD: password
      run: php artisan test
